### ISSUE TITLE
How to use it in Python or Java?

### ISSUE THREAD

**Issue by AbdullahXO** [tarekeldeeb/GloVe-Arabic#2]
Hello Tarek!

How to use the model in Python or Java? Do I really have to download (vectors and arabic_corpus) files (+3 GB) and then only search for words get the Glove value for each word?

**Comment by tarekeldeeb** [comment]
You only need 'vocab.txt', 'vectors.txt' to infer the model.

The arabic_corpus is only needed if you would like to re-train (remake the model)
