### ISSUE TITLE
Dimension of vectors?

### ISSUE THREAD

**Issue by Wafaa014** [tarekeldeeb/GloVe-Arabic#4]
Sorry for the question, but your documentation is somehow not clear.
What is the dimension of the Glove and Word2Vec vectors that are available in the archive file?
Is it 300 or 256?

**Comment by tarekeldeeb** [comment]
From [demo.sh](https://github.com/tarekeldeeb/GloVe-Arabic/blob/master/demo.sh) as well as [readme](https://github.com/tarekeldeeb/GloVe-Arabic/blob/master/README.md), both say the vector size is 256.
